const express = require('express')
const app = express()
const path = require('path')
const { db } = require('./db')
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/',express.static(path.join(__dirname,'public')))
app.use('/api',require('./routes/api').route)
db.sync()
  .then(() => {
    app.listen(7676)
  })